# fly.toml app configuration file generated for devdump on 2024-01-19T13:10:55+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "devdump"
primary_region = "cdg"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
